const items = [
  {
    heading: "IIS",
    haedingClass: "skill-4 skill",
    year: "6",
    yearClass: "year-4 year",
    proficiency: "Expert",
    proficiencyClass: "proficiency-4 proficiency",
  },
  {
    heading: "Microsoft Office",
    haedingClass: "skill-4 skill ILinux",
    year: "6",
    yearClass: "year-4 year",
    proficiency: "Expert",
    proficiencyClass: "proficiency-4 proficiency",
  },
  {
    heading: "Microsoft Excel",
    haedingClass: "skill-4 skill",
    year: "6",
    yearClass: "year-4 year",
    proficiency: "Expert",
    proficiencyClass: "proficiency-4 proficiency",
  },
  {
    heading: "Microsoft Outlook",
    haedingClass: "skill-1 skill  microsoft-outlook",
    year: "6",
    yearClass: "year-1 year",
    proficiency: "Expert",
    proficiencyClass: "proficiency-1 proficiency",
  },

  {
    heading: "Selenium RC / IDE",
    haedingClass: "skill-2 skill selenium",
    year: "2",
    yearClass: "year-2 year",
    proficiency: "Advanced",
    proficiencyClass: "proficiency-2 proficiency",
  },
  {
    heading: "Microsoft Visual Studio 2007 / 2010 / 2012/ 2015",
    haedingClass: "skill-2 skill image.png IMVS",
    year: "6",
    yearClass: "year-2 year",
    proficiency: "Advanced",
    proficiencyClass: "proficiency-2 proficiency",
  },
  {
    heading: "Nunit",
    haedingClass: "skill-4 skill",
    year: "2",
    yearClass: "year-4 year",
    proficiency: "Intermediate",
    proficiencyClass: "proficiency-4 proficiency",
  },

  {
    heading: "Elastic Search",
    haedingClass: "skill-1 skill",
    year: "4",
    yearClass: "year-1 year",
    proficiency: "Intermediate",
    proficiencyClass: "proficiency-1 proficiency",
  },
  {
    heading: "Active Direactory",
    haedingClass: "skill-2 skill ILinux",
    year: "3",
    yearClass: "year-2 year",
    proficiency: "Intermediate",
    proficiencyClass: "proficiency-2 proficiency",
  },
  {
    heading: "Apache",
    haedingClass: "skill-3 skill",
    year: "3",
    yearClass: "year-3 year",
    proficiency: "Intermediate",
    proficiencyClass: "proficiency-3 proficiency",
  },
  {
    heading: "WINS",
    haedingClass: "skill-4 skill",
    year: "2",
    yearClass: "year-4 year",
    proficiency: "Intermediate",
    proficiencyClass: "proficiency-4 proficiency",
  },

  {
    heading: "Acronis Backup",
    haedingClass: "skill-4 skill",
    year: "4",
    yearClass: "year-4 year",
    proficiency: "Intermediate",
    proficiencyClass: "proficiency-2 proficiency",
  },
  {
    heading: "Mail System",
    haedingClass: "skill-4 skill ILinux",
    year: "0.5",
    yearClass: "year-4 year",
    proficiency: "Intermediate",
    proficiencyClass: "proficiency-4 proficiency",
  },
  {
    heading: "KDE packages",
    haedingClass: "skill-1 skill",
    year: "1",
    yearClass: "year-1 year",
    proficiency: "Intermediate",
    proficiencyClass: "proficiency-1 proficiency",
  },
  {
    heading: "Microsoft SQL Server 2000 / 2005",
    haedingClass: "skill-2 skill MSQL",
    year: "2",
    yearClass: "year-2 year",
    proficiency: "Intermediate",
    proficiencyClass: "proficiency-2 proficiency",
  },

  {
    heading: "Jira",
    haedingClass: "skill-3 skill",
    year: "4",
    yearClass: "year-3 year",
    proficiency: "Intermediate",
    proficiencyClass: "proficiency-3 proficiency",
  },
  {
    heading: "Mantis",
    haedingClass: "skill-4 skill ILinux",
    year: "2",
    yearClass: "year-4 year",
    proficiency: "Intermediate",
    proficiencyClass: "proficiency-4 proficiency",
  },
  {
    heading: "PHPUnit",
    haedingClass: "skill-4 skill",
    year: "1.5",
    yearClass: "year-4 year",
    proficiency: "Beginner",
    proficiencyClass: "proficiency-4 proficiency",
  },
  {
    heading: "Ant",
    haedingClass: "skill-4 skill",
    year: "1",
    yearClass: "year-4 year",
    proficiency: "Beginner",
    proficiencyClass: "proficiency-4 proficiency",
  },

  {
    heading: "Junit",
    haedingClass: "skill-1 skill",
    year: "1.5",
    yearClass: "year-1 year",
    proficiency: "Beginner",
    proficiencyClass: "proficiency-1 proficiency",
  },
  {
    heading: "Eclipse IDE",
    haedingClass: "skill-3 skill ILinux",
    year: "1.5",
    yearClass: "year-3 year",
    proficiency: "Beginner",
    proficiencyClass: "proficiency-3 proficiency",
  },
  {
    heading: "NetBeans",
    haedingClass: "skill-4 skill",
    year: "0.5",
    yearClass: "year-4 year",
    proficiency: "Beginner",
    proficiencyClass: "proficiency-4 proficiency",
  },
  {
    heading: "XCode",
    haedingClass: "skill-4 skill",
    year: "1",
    yearClass: "year-4 year",
    proficiency: "Beginner",
    proficiencyClass: "proficiency-4 proficiency",
  },

  {
    heading: "DHCP",
    haedingClass: "skill-2 skill",
    year: "1,5",
    yearClass: "year-2 year",
    proficiency: "Beginner",
    proficiencyClass: "proficiency-2 proficiency",
  },
  {
    heading: "PHP My admin",
    haedingClass: "skill-4 skill ILinux",
    year: "1.5",
    yearClass: "year-4 year",
    proficiency: "Beginner",
    proficiencyClass: "proficiency-4 proficiency",
  },
  {
    heading: "MS Project",
    haedingClass: "skill-2 skill",
    year: "1.5",
    yearClass: "year-2 year",
    proficiency: "Beginner",
    proficiencyClass: "proficiency-2 proficiency",
  },
  {
    heading: "Redmine",
    haedingClass: "skill-4 skill",
    year: "1.5",
    yearClass: "year-4 year",
    proficiency: "Beginner",
    proficiencyClass: "proficiency-4 proficiency",
  },

  {
    heading: "eTrack",
    haedingClass: "skill-4 skill",
    year: "1",
    yearClass: "year-4 year",
    proficiency: "Beginner",
    proficiencyClass: "proficiency-2 proficiency",
  },
  {
    heading: "Toro",
    haedingClass: "skill-4 skill ILinux",
    year: "1",
    yearClass: "year-4 year",
    proficiency: "Beginner",
    proficiencyClass: "proficiency-4 proficiency",
  },
  {
    heading: "Test Complete",
    haedingClass: "skill-1 skill",
    year: "0.5",
    yearClass: "year-1 year",
    proficiency: "Beginner",
    proficiencyClass: "proficiency-1 proficiency",
  },
  {
    heading: "LoadRunner",
    haedingClass: "skill-3 skill",
    year: "0.5",
    yearClass: "year-3 year",
    proficiency: "Beginner",
    proficiencyClass: "proficiency-3 proficiency",
  },
];

export default items;
